source: .
markdown: kramdown
title: iOS Web Games
description: A Collection of high-quality games that can be played in Mobile Safari.
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one